import type { Account } from '../types';

export interface EBCRecord {
  isPAL: string;
  id: string;
  account: string;
  briefingTitle: string;
  briefingCenter: string;
  startDate: string;
  endDate: string;
  bpm: string;
  status: string;
  geo: string;
  bu: string;
  segment: string;
  region: string;
  industry: string;
  palPhase: string;
  isT2K: boolean;
  t2kCohort: string;
  isPartner: boolean;
  sfdcAccountId: string;
}

export function parseEBCCsv(csvText: string): EBCRecord[] {
  const lines = csvText.split('\n').filter(l => l.trim());
  if (lines.length < 2) return [];

  // Parse header (skip it, we use positional indexing)
  // const headers = parseCSVLine(lines[0]);

  return lines.slice(1).map(line => {
    const values = parseCSVLine(line);
    return {
      isPAL: values[0] || '',
      id: values[1] || '',
      account: values[2] || '',
      briefingTitle: values[3] || '',
      briefingCenter: values[4] || '',
      startDate: values[5] || '',
      endDate: values[6] || '',
      bpm: values[7] || '',
      status: values[8] || '',
      geo: values[9] || '',
      bu: values[10] || '',
      segment: values[11] || '',
      region: values[12] || '',
      industry: values[13] || '',
      palPhase: values[14] || '',
      isT2K: values[15]?.toLowerCase() === 'true',
      t2kCohort: values[16] || '',
      isPartner: values[17]?.toLowerCase() === 'true',
      sfdcAccountId: values[18] || '',
    };
  }).filter(r => r.account && r.status === 'InProgress');
}

function parseCSVLine(line: string): string[] {
  const result: string[] = [];
  let current = '';
  let inQuotes = false;

  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    if (char === '"') {
      if (inQuotes && line[i + 1] === '"') {
        current += '"';
        i++;
      } else {
        inQuotes = !inQuotes;
      }
    } else if (char === ',' && !inQuotes) {
      result.push(current.trim());
      current = '';
    } else {
      current += char;
    }
  }
  result.push(current.trim());
  return result;
}

/**
 * Convert EBC records into Account objects that the app can use.
 * Groups by account name (deduplicates multiple EBCs for same company).
 * Missing data (attendees, intelligence) will be generated by Bedrock.
 */
export function ebcRecordsToAccounts(records: EBCRecord[]): Account[] {
  // Group by account name
  // Group by unique EBC (account + briefing ID) — each EBC is a separate entry
  const seen = new Set<string>();
  const accounts: Account[] = [];

  for (const rec of records) {
    // Deduplicate by EBC ID (same EBC can appear multiple times with different BPMs)
    const ebcKey = `${rec.account}::${rec.id}::${rec.briefingTitle}`;
    if (seen.has(ebcKey)) continue;
    seen.add(ebcKey);

    const palPhaseToSmgs: Record<string, string> = {
      'GREENFIELD': 'Greenfield',
      'INVESTING': 'Invest',
      'INVESTING 1': 'Invest',
      'RAMPING': 'Migrate',
      'Ramping': 'Migrate',
      'SCALING': 'Optimize',
      'Investing': 'Invest',
    };

    accounts.push({
      customer_name: rec.account,
      industry: rec.industry || 'Technology',
      segment: rec.segment || 'ENT',
      geo: rec.geo || 'NAMER',
      sfdcAccountId: rec.sfdcAccountId || '',
      aws_spend: {
        current_year: -1, // Unknown from CSV — NOT zero
        prior_year: -1,
        ppa: '',
      },
      sfdc_data: {
        open_opps: 0,
        t2k: rec.isT2K,
        account_plan_priority: rec.briefingTitle || `${rec.industry} Transformation`,
        smgs_phase: palPhaseToSmgs[rec.palPhase] || rec.palPhase || 'Unknown',
      },
      ebc_data: {
        ebc_id: `EBC-${rec.id}`,
        meeting_dates: [rec.startDate.split(' ')[0]],
        themes: [rec.briefingTitle],
        attendees: [], // No fake attendees — we don't have this data
        location: rec.briefingCenter,
        requestor: `${rec.geo} ${rec.industry} Team`,
        status: rec.status || 'InProgress',
      },
      tc_current_state: {
        skill_builder: false,
        skill_builder_seats: 0,
        activation_rate: 0,
        certifications: 0,
        prior_engagement: '',
        renewal_date: '',
      },
      public_intelligence: {
        earnings_call_signals: [],
        linkedin_job_postings: { cloud_ai_roles: 0, yoy_change: '' },
        executive_social: [],
        glassdoor_signals: [],
        industry_context: `${rec.industry} sector undergoing cloud and AI transformation`,
        news_signals: [],
      },
      tc_opportunity_score: rec.isT2K ? 8 : (rec.palPhase === 'GREENFIELD' ? 8 : rec.palPhase === 'SCALING' ? 6 : 5),
      signals: [
        ...(rec.palPhase === 'GREENFIELD' ? [{ severity: 'HIGH' as const, label: 'Greenfield T&C', evidence: 'No structured T&C engagement' }] : []),
        ...(rec.isT2K ? [{ severity: 'HIGH' as const, label: 'T2K Account', evidence: `T2K Cohort: ${rec.t2kCohort || 'Priority'}` }] : []),
        { severity: 'MEDIUM' as const, label: 'EBC Scheduled', evidence: `${rec.briefingTitle} on ${rec.startDate.split(' ')[0]} at ${rec.briefingCenter}` },
      ],
    });
  }

  // Sort by score descending, then by EBC date ascending
  return accounts.sort((a, b) => b.tc_opportunity_score - a.tc_opportunity_score || 
    new Date(a.ebc_data.meeting_dates[0]).getTime() - new Date(b.ebc_data.meeting_dates[0]).getTime());
}
