import type { Account } from '../types';

export interface EBCRecord {
  isPAL: string;
  id: string;
  account: string;
  briefingTitle: string;
  briefingCenter: string;
  startDate: string;
  endDate: string;
  bpm: string;
  status: string;
  geo: string;
  bu: string;
  segment: string;
  region: string;
  industry: string;
  palPhase: string;
  isT2K: boolean;
  t2kCohort: string;
  isPartner: boolean;
  sfdcAccountId: string;
}

export function parseEBCCsv(csvText: string): EBCRecord[] {
  const lines = csvText.split('\n').filter(l => l.trim());
  if (lines.length < 2) return [];

  // Parse header (skip it, we use positional indexing)
  // const headers = parseCSVLine(lines[0]);

  return lines.slice(1).map(line => {
    const values = parseCSVLine(line);
    return {
      isPAL: values[0] || '',
      id: values[1] || '',
      account: values[2] || '',
      briefingTitle: values[3] || '',
      briefingCenter: values[4] || '',
      startDate: values[5] || '',
      endDate: values[6] || '',
      bpm: values[7] || '',
      status: values[8] || '',
      geo: values[9] || '',
      bu: values[10] || '',
      segment: values[11] || '',
      region: values[12] || '',
      industry: values[13] || '',
      palPhase: values[14] || '',
      isT2K: values[15]?.toLowerCase() === 'true',
      t2kCohort: values[16] || '',
      isPartner: values[17]?.toLowerCase() === 'true',
      sfdcAccountId: values[18] || '',
    };
  }).filter(r => r.account && r.status === 'InProgress');
}

function parseCSVLine(line: string): string[] {
  const result: string[] = [];
  let current = '';
  let inQuotes = false;

  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    if (char === '"') {
      if (inQuotes && line[i + 1] === '"') {
        current += '"';
        i++;
      } else {
        inQuotes = !inQuotes;
      }
    } else if (char === ',' && !inQuotes) {
      result.push(current.trim());
      current = '';
    } else {
      current += char;
    }
  }
  result.push(current.trim());
  return result;
}

/**
 * Convert EBC records into Account objects that the app can use.
 * Groups by account name (deduplicates multiple EBCs for same company).
 * Missing data (attendees, intelligence) will be generated by Bedrock.
 */
export function ebcRecordsToAccounts(records: EBCRecord[]): Account[] {
  // Group by account name
  const grouped = new Map<string, EBCRecord[]>();
  for (const r of records) {
    const key = r.account;
    if (!grouped.has(key)) grouped.set(key, []);
    grouped.get(key)!.push(r);
  }

  const accounts: Account[] = [];
  for (const [name, recs] of grouped) {
    const primary = recs[0];
    // Sort EBCs by date, take the nearest upcoming one
    const sorted = [...recs].sort((a, b) => new Date(a.startDate).getTime() - new Date(b.startDate).getTime());
    const nextEbc = sorted[0];

    const palPhaseToSmgs: Record<string, string> = {
      'GREENFIELD': 'Greenfield',
      'INVESTING': 'Invest',
      'INVESTING 1': 'Invest',
      'RAMPING': 'Migrate',
      'Ramping': 'Migrate',
      'SCALING': 'Optimize',
      'Investing': 'Invest',
    };

    accounts.push({
      customer_name: name,
      industry: primary.industry || 'Technology',
      segment: primary.segment || 'ENT',
      geo: primary.geo || 'NAMER',
      aws_spend: {
        current_year: 0, // Unknown from CSV — Bedrock will estimate
        prior_year: 0,
        ppa: '',
      },
      sfdc_data: {
        open_opps: 0,
        t2k: primary.isT2K,
        account_plan_priority: nextEbc.briefingTitle || `${primary.industry} Transformation`,
        smgs_phase: palPhaseToSmgs[primary.palPhase] || primary.palPhase || 'Unknown',
      },
      ebc_data: {
        ebc_id: `EBC-${nextEbc.id}`,
        meeting_dates: [nextEbc.startDate.split(' ')[0]],
        themes: recs.map(r => r.briefingTitle).filter((v, i, a) => a.indexOf(v) === i),
        attendees: [], // Will be populated by Bedrock
        location: nextEbc.briefingCenter,
        requestor: `${primary.geo} ${primary.industry} Team`,
      },
      tc_current_state: {
        skill_builder: false,
        skill_builder_seats: 0,
        activation_rate: 0,
        certifications: 0,
        prior_engagement: 'Unknown — to be researched',
        renewal_date: '',
      },
      public_intelligence: {
        earnings_call_signals: [],
        linkedin_job_postings: { cloud_ai_roles: 0, yoy_change: '' },
        executive_social: [],
        glassdoor_signals: [],
        industry_context: '',
        news_signals: [],
      },
      tc_opportunity_score: primary.isT2K ? 7 : (primary.palPhase === 'GREENFIELD' ? 8 : 5),
      signals: [
        ...(primary.palPhase === 'GREENFIELD' ? [{ severity: 'HIGH' as const, label: 'Greenfield T&C', evidence: 'No structured T&C engagement' }] : []),
        ...(primary.isT2K ? [{ severity: 'HIGH' as const, label: 'T2K Account', evidence: `T2K Cohort: ${primary.t2kCohort || 'Priority'}` }] : []),
        { severity: 'MEDIUM' as const, label: 'EBC Scheduled', evidence: `${nextEbc.briefingTitle} on ${nextEbc.startDate.split(' ')[0]} at ${nextEbc.briefingCenter}` },
      ],
    });
  }

  // Sort by score descending, then by EBC date ascending
  return accounts.sort((a, b) => b.tc_opportunity_score - a.tc_opportunity_score || 
    new Date(a.ebc_data.meeting_dates[0]).getTime() - new Date(b.ebc_data.meeting_dates[0]).getTime());
}
